### ISSUE TITLE
url to add

### ISSUE THREAD

**Issue by robmarkcole** [tejasri19/EuroSAT_data_analysis#2]
https://www.researchgate.net/publication/374879127_Performance_Comparison_of_Multispectral_Channels_for_Land_Use_Classification

Is the paper available on arxiv of elsewhere also? I cannot access it

**Comment by tejasri19** [comment]
> https://www.researchgate.net/publication/374879127_Performance_Comparison_of_Multispectral_Channels_for_Land_Use_Classification
> 
> Is the paper available on arxiv of elsewhere also? I cannot access it

The paper can be accessed here: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10283090

**Comment by robmarkcole** [comment]
Needs institutional account to access - with my level of access I only see 

<img width="311" alt="image" src="https://github.com/tejasri19/EuroSAT_data_analysis/assets/11855322/2cc86ea9-aee8-42a0-ab06-2d302547f4cb">

**Comment by Soumyabrata** [comment]
> Needs institutional account to access - with my level of access I only see
> <img alt="image" width="311" src="https://private-user-images.githubusercontent.com/11855322/291969595-2cc86ea9-aee8-42a0-ab06-2d302547f4cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNzkwMDYsIm5iZiI6MTcwOTM3ODcwNiwicGF0aCI6Ii8xMTg1NTMyMi8yOTE5Njk1OTUtMmNjODZlYTktYWVlOC00MmEwLWFiMDYtMmQzMDI1NDdmNGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDExMjUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYTgyMmZjMTlmNjExNjBlOTNjZjcyODE5YjJmZmFhMjNjMTQ5ZDY3NzQzODM2OTk5MzQzZTBjMmFlNjJlN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R86pcQZXJCBjF602gHsVo8Ag2PRRckl_aBL3dzOtCVc">

Hi. The paper is now uploaded to the GitHub repo as `manuscript.pdf`. Sorry for the delay in responding to your request.
